/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDatasetsIndexRouteImport } from './routes/_authenticated/datasets.index'
import { Route as ApiAiTranscribeRouteImport } from './routes/api/ai/transcribe'
import { Route as ApiAiExtractSymptomsRouteImport } from './routes/api/ai/extract-symptoms'
import { Route as AuthenticatedParticipantsIdRouteImport } from './routes/_authenticated/participants.$id'
import { Route as AuthenticatedLogWearableRouteImport } from './routes/_authenticated/log.wearable'
import { Route as AuthenticatedLogVoiceRouteImport } from './routes/_authenticated/log.voice'
import { Route as AuthenticatedLogSymptomsRouteImport } from './routes/_authenticated/log.symptoms'
import { Route as AuthenticatedLogLabsRouteImport } from './routes/_authenticated/log.labs'
import { Route as AuthenticatedLogFoodRouteImport } from './routes/_authenticated/log.food'
import { Route as AuthenticatedLogEhrRouteImport } from './routes/_authenticated/log.ehr'
import { Route as AuthenticatedLogBrainRouteImport } from './routes/_authenticated/log.brain'
import { Route as AuthenticatedDatasetsRequestRouteImport } from './routes/_authenticated/datasets.request'
import { Route as AuthenticatedDatasetsStudyIdRouteImport } from './routes/_authenticated/datasets.$studyId'
import { Route as AuthenticatedAdminStudiesRouteImport } from './routes/_authenticated/admin.studies'
import { Route as AuthenticatedAdminDatasetRequestsRouteImport } from './routes/_authenticated/admin.dataset-requests'
import { Route as AuthenticatedAdminConsentsRouteImport } from './routes/_authenticated/admin.consents'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsIndexRoute =
  AuthenticatedDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAiTranscribeRoute = ApiAiTranscribeRouteImport.update({
  id: '/api/ai/transcribe',
  path: '/api/ai/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExtractSymptomsRoute = ApiAiExtractSymptomsRouteImport.update({
  id: '/api/ai/extract-symptoms',
  path: '/api/ai/extract-symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParticipantsIdRoute =
  AuthenticatedParticipantsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedParticipantsRoute,
  } as any)
const AuthenticatedLogWearableRoute =
  AuthenticatedLogWearableRouteImport.update({
    id: '/log/wearable',
    path: '/log/wearable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogVoiceRoute = AuthenticatedLogVoiceRouteImport.update({
  id: '/log/voice',
  path: '/log/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogSymptomsRoute =
  AuthenticatedLogSymptomsRouteImport.update({
    id: '/log/symptoms',
    path: '/log/symptoms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogLabsRoute = AuthenticatedLogLabsRouteImport.update({
  id: '/log/labs',
  path: '/log/labs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogFoodRoute = AuthenticatedLogFoodRouteImport.update({
  id: '/log/food',
  path: '/log/food',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogEhrRoute = AuthenticatedLogEhrRouteImport.update({
  id: '/log/ehr',
  path: '/log/ehr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogBrainRoute = AuthenticatedLogBrainRouteImport.update({
  id: '/log/brain',
  path: '/log/brain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsRequestRoute =
  AuthenticatedDatasetsRequestRouteImport.update({
    id: '/datasets/request',
    path: '/datasets/request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsStudyIdRoute =
  AuthenticatedDatasetsStudyIdRouteImport.update({
    id: '/datasets/$studyId',
    path: '/datasets/$studyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudiesRoute =
  AuthenticatedAdminStudiesRouteImport.update({
    id: '/admin/studies',
    path: '/admin/studies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDatasetRequestsRoute =
  AuthenticatedAdminDatasetRequestsRouteImport.update({
    id: '/admin/dataset-requests',
    path: '/admin/dataset-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConsentsRoute =
  AuthenticatedAdminConsentsRouteImport.update({
    id: '/admin/consents',
    path: '/admin/consents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/export': typeof AuthenticatedExportRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/participants': typeof AuthenticatedParticipantsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/consents': typeof AuthenticatedAdminConsentsRoute
  '/admin/dataset-requests': typeof AuthenticatedAdminDatasetRequestsRoute
  '/admin/studies': typeof AuthenticatedAdminStudiesRoute
  '/datasets/$studyId': typeof AuthenticatedDatasetsStudyIdRoute
  '/datasets/request': typeof AuthenticatedDatasetsRequestRoute
  '/log/brain': typeof AuthenticatedLogBrainRoute
  '/log/ehr': typeof AuthenticatedLogEhrRoute
  '/log/food': typeof AuthenticatedLogFoodRoute
  '/log/labs': typeof AuthenticatedLogLabsRoute
  '/log/symptoms': typeof AuthenticatedLogSymptomsRoute
  '/log/voice': typeof AuthenticatedLogVoiceRoute
  '/log/wearable': typeof AuthenticatedLogWearableRoute
  '/participants/$id': typeof AuthenticatedParticipantsIdRoute
  '/api/ai/extract-symptoms': typeof ApiAiExtractSymptomsRoute
  '/api/ai/transcribe': typeof ApiAiTranscribeRoute
  '/datasets/': typeof AuthenticatedDatasetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/export': typeof AuthenticatedExportRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/participants': typeof AuthenticatedParticipantsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/consents': typeof AuthenticatedAdminConsentsRoute
  '/admin/dataset-requests': typeof AuthenticatedAdminDatasetRequestsRoute
  '/admin/studies': typeof AuthenticatedAdminStudiesRoute
  '/datasets/$studyId': typeof AuthenticatedDatasetsStudyIdRoute
  '/datasets/request': typeof AuthenticatedDatasetsRequestRoute
  '/log/brain': typeof AuthenticatedLogBrainRoute
  '/log/ehr': typeof AuthenticatedLogEhrRoute
  '/log/food': typeof AuthenticatedLogFoodRoute
  '/log/labs': typeof AuthenticatedLogLabsRoute
  '/log/symptoms': typeof AuthenticatedLogSymptomsRoute
  '/log/voice': typeof AuthenticatedLogVoiceRoute
  '/log/wearable': typeof AuthenticatedLogWearableRoute
  '/participants/$id': typeof AuthenticatedParticipantsIdRoute
  '/api/ai/extract-symptoms': typeof ApiAiExtractSymptomsRoute
  '/api/ai/transcribe': typeof ApiAiTranscribeRoute
  '/datasets': typeof AuthenticatedDatasetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/participants': typeof AuthenticatedParticipantsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/consents': typeof AuthenticatedAdminConsentsRoute
  '/_authenticated/admin/dataset-requests': typeof AuthenticatedAdminDatasetRequestsRoute
  '/_authenticated/admin/studies': typeof AuthenticatedAdminStudiesRoute
  '/_authenticated/datasets/$studyId': typeof AuthenticatedDatasetsStudyIdRoute
  '/_authenticated/datasets/request': typeof AuthenticatedDatasetsRequestRoute
  '/_authenticated/log/brain': typeof AuthenticatedLogBrainRoute
  '/_authenticated/log/ehr': typeof AuthenticatedLogEhrRoute
  '/_authenticated/log/food': typeof AuthenticatedLogFoodRoute
  '/_authenticated/log/labs': typeof AuthenticatedLogLabsRoute
  '/_authenticated/log/symptoms': typeof AuthenticatedLogSymptomsRoute
  '/_authenticated/log/voice': typeof AuthenticatedLogVoiceRoute
  '/_authenticated/log/wearable': typeof AuthenticatedLogWearableRoute
  '/_authenticated/participants/$id': typeof AuthenticatedParticipantsIdRoute
  '/api/ai/extract-symptoms': typeof ApiAiExtractSymptomsRoute
  '/api/ai/transcribe': typeof ApiAiTranscribeRoute
  '/_authenticated/datasets/': typeof AuthenticatedDatasetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/export'
    | '/history'
    | '/onboarding'
    | '/participants'
    | '/settings'
    | '/today'
    | '/admin/audit'
    | '/admin/consents'
    | '/admin/dataset-requests'
    | '/admin/studies'
    | '/datasets/$studyId'
    | '/datasets/request'
    | '/log/brain'
    | '/log/ehr'
    | '/log/food'
    | '/log/labs'
    | '/log/symptoms'
    | '/log/voice'
    | '/log/wearable'
    | '/participants/$id'
    | '/api/ai/extract-symptoms'
    | '/api/ai/transcribe'
    | '/datasets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/export'
    | '/history'
    | '/onboarding'
    | '/participants'
    | '/settings'
    | '/today'
    | '/admin/audit'
    | '/admin/consents'
    | '/admin/dataset-requests'
    | '/admin/studies'
    | '/datasets/$studyId'
    | '/datasets/request'
    | '/log/brain'
    | '/log/ehr'
    | '/log/food'
    | '/log/labs'
    | '/log/symptoms'
    | '/log/voice'
    | '/log/wearable'
    | '/participants/$id'
    | '/api/ai/extract-symptoms'
    | '/api/ai/transcribe'
    | '/datasets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/export'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/participants'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/consents'
    | '/_authenticated/admin/dataset-requests'
    | '/_authenticated/admin/studies'
    | '/_authenticated/datasets/$studyId'
    | '/_authenticated/datasets/request'
    | '/_authenticated/log/brain'
    | '/_authenticated/log/ehr'
    | '/_authenticated/log/food'
    | '/_authenticated/log/labs'
    | '/_authenticated/log/symptoms'
    | '/_authenticated/log/voice'
    | '/_authenticated/log/wearable'
    | '/_authenticated/participants/$id'
    | '/api/ai/extract-symptoms'
    | '/api/ai/transcribe'
    | '/_authenticated/datasets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiExtractSymptomsRoute: typeof ApiAiExtractSymptomsRoute
  ApiAiTranscribeRoute: typeof ApiAiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/': {
      id: '/_authenticated/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof AuthenticatedDatasetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai/transcribe': {
      id: '/api/ai/transcribe'
      path: '/api/ai/transcribe'
      fullPath: '/api/ai/transcribe'
      preLoaderRoute: typeof ApiAiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/extract-symptoms': {
      id: '/api/ai/extract-symptoms'
      path: '/api/ai/extract-symptoms'
      fullPath: '/api/ai/extract-symptoms'
      preLoaderRoute: typeof ApiAiExtractSymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/participants/$id': {
      id: '/_authenticated/participants/$id'
      path: '/$id'
      fullPath: '/participants/$id'
      preLoaderRoute: typeof AuthenticatedParticipantsIdRouteImport
      parentRoute: typeof AuthenticatedParticipantsRoute
    }
    '/_authenticated/log/wearable': {
      id: '/_authenticated/log/wearable'
      path: '/log/wearable'
      fullPath: '/log/wearable'
      preLoaderRoute: typeof AuthenticatedLogWearableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/voice': {
      id: '/_authenticated/log/voice'
      path: '/log/voice'
      fullPath: '/log/voice'
      preLoaderRoute: typeof AuthenticatedLogVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/symptoms': {
      id: '/_authenticated/log/symptoms'
      path: '/log/symptoms'
      fullPath: '/log/symptoms'
      preLoaderRoute: typeof AuthenticatedLogSymptomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/labs': {
      id: '/_authenticated/log/labs'
      path: '/log/labs'
      fullPath: '/log/labs'
      preLoaderRoute: typeof AuthenticatedLogLabsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/food': {
      id: '/_authenticated/log/food'
      path: '/log/food'
      fullPath: '/log/food'
      preLoaderRoute: typeof AuthenticatedLogFoodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/ehr': {
      id: '/_authenticated/log/ehr'
      path: '/log/ehr'
      fullPath: '/log/ehr'
      preLoaderRoute: typeof AuthenticatedLogEhrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log/brain': {
      id: '/_authenticated/log/brain'
      path: '/log/brain'
      fullPath: '/log/brain'
      preLoaderRoute: typeof AuthenticatedLogBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/request': {
      id: '/_authenticated/datasets/request'
      path: '/datasets/request'
      fullPath: '/datasets/request'
      preLoaderRoute: typeof AuthenticatedDatasetsRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets/$studyId': {
      id: '/_authenticated/datasets/$studyId'
      path: '/datasets/$studyId'
      fullPath: '/datasets/$studyId'
      preLoaderRoute: typeof AuthenticatedDatasetsStudyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/studies': {
      id: '/_authenticated/admin/studies'
      path: '/admin/studies'
      fullPath: '/admin/studies'
      preLoaderRoute: typeof AuthenticatedAdminStudiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dataset-requests': {
      id: '/_authenticated/admin/dataset-requests'
      path: '/admin/dataset-requests'
      fullPath: '/admin/dataset-requests'
      preLoaderRoute: typeof AuthenticatedAdminDatasetRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/consents': {
      id: '/_authenticated/admin/consents'
      path: '/admin/consents'
      fullPath: '/admin/consents'
      preLoaderRoute: typeof AuthenticatedAdminConsentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedParticipantsRouteChildren {
  AuthenticatedParticipantsIdRoute: typeof AuthenticatedParticipantsIdRoute
}

const AuthenticatedParticipantsRouteChildren: AuthenticatedParticipantsRouteChildren =
  {
    AuthenticatedParticipantsIdRoute: AuthenticatedParticipantsIdRoute,
  }

const AuthenticatedParticipantsRouteWithChildren =
  AuthenticatedParticipantsRoute._addFileChildren(
    AuthenticatedParticipantsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminConsentsRoute: typeof AuthenticatedAdminConsentsRoute
  AuthenticatedAdminDatasetRequestsRoute: typeof AuthenticatedAdminDatasetRequestsRoute
  AuthenticatedAdminStudiesRoute: typeof AuthenticatedAdminStudiesRoute
  AuthenticatedDatasetsStudyIdRoute: typeof AuthenticatedDatasetsStudyIdRoute
  AuthenticatedDatasetsRequestRoute: typeof AuthenticatedDatasetsRequestRoute
  AuthenticatedLogBrainRoute: typeof AuthenticatedLogBrainRoute
  AuthenticatedLogEhrRoute: typeof AuthenticatedLogEhrRoute
  AuthenticatedLogFoodRoute: typeof AuthenticatedLogFoodRoute
  AuthenticatedLogLabsRoute: typeof AuthenticatedLogLabsRoute
  AuthenticatedLogSymptomsRoute: typeof AuthenticatedLogSymptomsRoute
  AuthenticatedLogVoiceRoute: typeof AuthenticatedLogVoiceRoute
  AuthenticatedLogWearableRoute: typeof AuthenticatedLogWearableRoute
  AuthenticatedDatasetsIndexRoute: typeof AuthenticatedDatasetsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminConsentsRoute: AuthenticatedAdminConsentsRoute,
  AuthenticatedAdminDatasetRequestsRoute:
    AuthenticatedAdminDatasetRequestsRoute,
  AuthenticatedAdminStudiesRoute: AuthenticatedAdminStudiesRoute,
  AuthenticatedDatasetsStudyIdRoute: AuthenticatedDatasetsStudyIdRoute,
  AuthenticatedDatasetsRequestRoute: AuthenticatedDatasetsRequestRoute,
  AuthenticatedLogBrainRoute: AuthenticatedLogBrainRoute,
  AuthenticatedLogEhrRoute: AuthenticatedLogEhrRoute,
  AuthenticatedLogFoodRoute: AuthenticatedLogFoodRoute,
  AuthenticatedLogLabsRoute: AuthenticatedLogLabsRoute,
  AuthenticatedLogSymptomsRoute: AuthenticatedLogSymptomsRoute,
  AuthenticatedLogVoiceRoute: AuthenticatedLogVoiceRoute,
  AuthenticatedLogWearableRoute: AuthenticatedLogWearableRoute,
  AuthenticatedDatasetsIndexRoute: AuthenticatedDatasetsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiExtractSymptomsRoute: ApiAiExtractSymptomsRoute,
  ApiAiTranscribeRoute: ApiAiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
